import argparse
import sys
import time
from pathlib import Path

import nibabel as nib
import numpy as np
from skimage import measure

def load_mask(mask_path: Path):
    """
    Loads a NIfTI segmentation mask, extracts the voxel array,
    and retrieves the voxel spacing.
    """
    if not mask_path.exists():
        raise FileNotFoundError(f"Mask file not found: {mask_path}")
        
    img = nib.load(str(mask_path))
    
    # Extract the voxel data as a numpy array
    data = img.get_fdata()
    
    # Ensure it's a binary mask (some might have probabilities, though TotalSegmentator usually returns int)
    # We threshold at 0.5 to safely binarize in case of floating point representations.
    data = (data > 0.5).astype(np.uint8)
    
    # Extract voxel spacing (zooms) from the NIfTI header
    # Usually a tuple like (1.5, 1.5, 1.5) representing mm per voxel in x, y, z
    spacing = img.header.get_zooms()[:3]
    
    return data, spacing

def generate_mesh_from_mask(mask_data: np.ndarray, spacing: tuple):
    """
    Generates a 3D surface mesh from a binary 3D mask using the Marching Cubes algorithm.
    The 'spacing' parameter ensures that the resulting vertices represent true physical coordinates
    in millimeters, rather than abstract voxel indices.
    """
    # Marching cubes finds the isosurface at a specific level.
    # Since our mask is binary (0 and 1), a level of 0.5 is ideal for the boundary.
    # The `spacing` argument scales the output vertex coordinates automatically.
    verts, faces, normals, values = measure.marching_cubes(mask_data, level=0.5, spacing=spacing)
    return verts, faces

def save_mesh_as_obj(filepath: Path, verts: np.ndarray, faces: np.ndarray):
    """
    Saves vertices and faces as a Wavefront .obj file.
    .obj is a standard, widely-supported 3D format that is plain-text,
    making it easy to generate without extra dependencies.
    """
    with open(filepath, 'w') as f:
        f.write(f"# Generated by Medical Surgery Planner\n")
        f.write(f"# Vertices: {len(verts)}\n")
        f.write(f"# Faces: {len(faces)}\n\n")
        
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            
        for face in faces:
            # .obj indices are 1-based
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

def process_organ(organ_name: str, segmentations_dir: Path, output_dir: Path):
    print(f"\n--- Processing Organ: {organ_name} ---")
    
    mask_filename = f"{organ_name}.nii.gz"
    mask_path = segmentations_dir / mask_filename
    
    if not mask_path.exists():
        print(f"[ERROR] Could not find mask for {organ_name} at {mask_path}")
        return False
        
    start_time = time.time()
    
    try:
        # 1. Load data
        print("[INFO] Loading NIfTI mask...")
        mask_data, spacing = load_mask(mask_path)
        foreground_voxels = np.sum(mask_data)
        
        print(f"       Mask shape: {mask_data.shape}")
        print(f"       Voxel spacing: {spacing}")
        print(f"       Foreground voxels: {foreground_voxels}")
        
        if foreground_voxels == 0:
            print(f"[WARNING] Mask for {organ_name} is empty (no foreground voxels). Skipping mesh generation.")
            return False
            
        # 2. Generate mesh
        print("[INFO] Running Marching Cubes...")
        verts, faces = generate_mesh_from_mask(mask_data, spacing)
        
        # 3. Basic cleanup / Validation
        if len(verts) == 0 or len(faces) == 0:
             print(f"[WARNING] Marching cubes produced an empty mesh for {organ_name}.")
             return False
             
        # Calculate bounding box & dimensions
        min_coords = verts.min(axis=0)
        max_coords = verts.max(axis=0)
        dimensions = max_coords - min_coords
        
        print(f"       Vertices: {len(verts)}")
        print(f"       Faces: {len(faces)}")
        print(f"       Bounding Box Min: {np.round(min_coords, 2)}")
        print(f"       Bounding Box Max: {np.round(max_coords, 2)}")
        print(f"       Physical Dimensions (mm): {np.round(dimensions, 2)}")
        
        # 4. Save mesh
        output_filepath = output_dir / f"{organ_name}.obj"
        print(f"[INFO] Saving mesh to {output_filepath}...")
        save_mesh_as_obj(output_filepath, verts, faces)
        
        runtime = time.time() - start_time
        print(f"[SUCCESS] {organ_name} processed in {runtime:.2f} seconds.")
        return True
        
    except Exception as e:
        print(f"[ERROR] Failed to process {organ_name}: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    parser = argparse.ArgumentParser(description="Generate 3D meshes from NIfTI segmentation masks using Marching Cubes.")
    parser.add_argument("--organs", nargs="+", required=True, help="List of organs to process (e.g., liver heart aorta)")
    parser.add_argument("--input-dir", type=str, default="outputs/segmentations", help="Directory containing .nii.gz masks")
    parser.add_argument("--output-dir", type=str, default="outputs/meshes", help="Directory to save generated meshes")
    
    args = parser.parse_args()
    
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    
    successful = 0
    for organ in args.organs:
        success = process_organ(organ, input_dir, output_dir)
        if success:
            successful += 1
            
    print(f"\n======================================")
    print(f"Finished. Successfully generated {successful}/{len(args.organs)} meshes.")
    print(f"Meshes are saved in: {output_dir.absolute()}")
    print(f"======================================")

if __name__ == "__main__":
    main()
